### ISSUE TITLE
1.2.3 and 1.3.1 Crashing Randomly 

### ISSUE THREAD

**Issue by iluvspidrs** [FiveNights21611/dark-infection-stuff#1]
Typically this crash happens when interacting with an entity or block. This has also happened when falling into the water and triggering a raid. My friends and I love this mod and hope to continue playing! Index 79, 80, and 81 have been mentioned during all crashes. 

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/5/23, 3:45 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index 79 out of bounds for length 0
	at net.minecraftforge.eventbus.ListenerList.unregister(ListenerList.java:133) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.ListenerList.unregisterAll(ListenerList.java:140) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.unregister(EventBus.java:277) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.mcreator.darkinfection.procedures.InfectedProcedure$1.run(InfectedProcedure.java:191) ~[DI-1.2.3.jar%2369!/:?] {re:classloading,pl:eventbus:A}
	at net.mcreator.darkinfection.procedures.InfectedProcedure$1.tick(InfectedProcedure.java:54) ~[DI-1.2.3.jar%2369!/:?] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_1321__tick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:953) ~[forge-1.18.2-40.2.0-universal.jar%23135!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:otyacraftengine-common.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23130!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2960372984 bytes (2823 MiB) / 8522825728 bytes (8128 MiB) up to 42949672960 bytes (40960 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75183.96
	Virtual memory used (MB): 20273.43
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx40G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['iluvspidrs'/93, l='ServerLevel[Hadley]', x=285.22, y=107.00, z=496.25]]
	Data Packs: vanilla, mod:smartbrainlib (incompatible), mod:hexerei (incompatible), mod:saturn, mod:inventorysorter (incompatible), mod:supermartijn642configlib, mod:dark_infection, mod:gbook (incompatible), mod:weeping_angels (incompatible), mod:additional_enchanting, mod:simple_hearts, mod:observed (incompatible), mod:jei (incompatible), mod:graveyard (incompatible), mod:majruszsdifficulty (incompatible), mod:the_banished, mod:the_cataclysm, mod:immortuoscalyx (incompatible), mod:decorative_blocks, mod:gemsnjewels, mod:fullturtlearmor (incompatible), mod:guideapi_vp (incompatible), mod:ddenizens, mod:drunken_mug, mod:hordes (incompatible), mod:shc, mod:infection_of_the_end, mod:crafttweaker (incompatible), mod:hauntedharvest (incompatible), mod:cloth_config (incompatible), mod:forge, mod:twilightforest (incompatible), mod:truebackrooms, mod:decapitation (incompatible), mod:selene (incompatible), mod:supplementaries (incompatible), mod:cofh_core, mod:undead_expansion, mod:itshallnottick (incompatible), mod:terrablender (incompatible), mod:biomesoplenty (incompatible), mod:supermartijn642corelib, mod:omgourd, mod:born_in_chaos_v1, mod:accbackrooms, mod:whisperwoods (incompatible), mod:curios (incompatible), mod:patchouli (incompatible), mod:xaerominimap, mod:gravestone (incompatible), mod:extlights, mod:slenderman, mod:infinitymending (incompatible), mod:chider001, mod:gottschcore (incompatible), mod:modonomicon, mod:atlaslib (incompatible), mod:armor_weight, mod:wormhole, mod:architectury (incompatible), mod:otyacraftengine (incompatible), mod:iammusicplayer (incompatible), mod:vampirism (incompatible), mod:vampiresneedumbrellas (incompatible), mod:werewolves (incompatible), mod:ferritecore (incompatible), mod:occultism, mod:majruszlib (incompatible), mod:enhancedcelestials (incompatible), mod:voidscape (incompatible), mod:majruszsenchantments (incompatible), mod:sniper_mod, mod:letmedespawn (incompatible), mod:cosmeticarmorreworked (incompatible), mod:choochoocharlescraft, mod:witching_hour, mod:suszombification (incompatible), mod:geckolib3 (incompatible), Supplementaries Generated Pack
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		SmartBrainLib-forge-1.18.2-1.7.4.jar              |SmartBrainLib                 |smartbrainlib                 |1.7.4               |DONE      |Manifest: NOSIGNATURE
		hexerei-0.2.2.jar                                 |Hexerei                       |hexerei                       |0.2.2               |DONE      |Manifest: NOSIGNATURE
		saturn-mc1.18.2-0.0.1.jar                         |Saturn                        |saturn                        |0.0.1               |DONE      |Manifest: NOSIGNATURE
		Inventory-Sorter-Mod-1.18.2.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		DI-1.2.3.jar                                      |The Dark Infection            |dark_infection                |1.2.3               |DONE      |Manifest: NOSIGNATURE
		Guidebook-1.18.2-3.4.3.jar                        |Guidebook                     |gbook                         |3.4.3               |DONE      |Manifest: NOSIGNATURE
		weeping_angels-1.0.1.jar                          |Weeping Angels                |weeping_angels                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchanting1.71.18.2.jar                 |Additional Enchanting         |additional_enchanting         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		simpleheartsbeta.jar                              |Simple Hearts                 |simple_hearts                 |1.1.3               |DONE      |Manifest: NOSIGNATURE
		observed-1.2.2-1.18.jar                           |Observed                      |observed                      |1.2.2-1.18          |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.5.174.jar                          |Just Enough Items             |jei                           |9.5.5.174           |DONE      |Manifest: NOSIGNATURE
		The_Graveyard_1.9.1_(FORGE)_for_1.18.2.jar        |The Graveyard                 |graveyard                     |1.9.1               |DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-1.18.2-1.4.4.jar              |Majrusz's Progressive Difficul|majruszsdifficulty            |1.4.4               |DONE      |Manifest: NOSIGNATURE
		The-Banished-1.0-1.18.2.jar                       |The Banished                  |the_banished                  |1.0.0               |DONE      |Manifest: NOSIGNATURE
		TheCataclysm-1.0.1.jar                            |The Cataclysm                 |the_cataclysm                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		immortuoscalyx-1.18.2-1.6.4.jar                   |Immortuos Calyx               |immortuoscalyx                |1.18.2-1.6.4        |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		gemsnjewels-1.18.2-0.6.1.jar                      |Gems & Jewels                 |gemsnjewels                   |0.6.1               |DONE      |Manifest: NOSIGNATURE
		FullTurtleArmor-1.2-FORGE-MC1.18.jar              |Full Turtle Armor             |fullturtlearmor               |1.2                 |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.18.1-2.2.3.jar                     |Guide-API VP                  |guideapi_vp                   |2.2.3               |DONE      |Manifest: NOSIGNATURE
		DungeonDenizens-mc1.18.2-f40.1.0-v1.0.0.jar       |Dungeon Denizens              |ddenizens                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		drunken_mug-1.18.2-1.0.1.jar                      |Drunken Mug                   |drunken_mug                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		The-Hordes-1.18.2-1.1.5e.jar                      |The Hordes                    |hordes                        |1.1.5e              |DONE      |Manifest: NOSIGNATURE
		SHC1.02.jar                                       |SpankstersHorrorCraft         |shc                           |1.0.0               |DONE      |Manifest: NOSIGNATURE
		InfectionOfTheEnd+-+Forge++40.0.0+to+40.1.69.jar  |Infection of the End          |infection_of_the_end          |1.3.4               |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.197.jar             |CraftTweaker                  |crafttweaker                  |9.1.197             |DONE      |Manifest: NOSIGNATURE
		hauntedharvest-1.18.2-1.7.7.jar                   |Haunted Harvest               |hauntedharvest                |1.18.2-1.7.7        |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.18.2-4.1.1423-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1423            |DONE      |Manifest: NOSIGNATURE
		TheTrueBackroomsV.7.jar                           |TrueBackrooms                 |truebackrooms                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Decapitation-Mod-Forge-1.18.2.jar                 |Decapitated                   |decapitation                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.4.7.jar                  |Supplementaries               |supplementaries               |1.18.2-1.4.7        |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.18.2-9.1.2.32.jar                     |CoFH Core                     |cofh_core                     |9.1.2.32            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		UndeadExpansion_2.0.4_1.18.2_b.jar                |Undead Expansion              |undead_expansion              |2.0.4               |DONE      |Manifest: NOSIGNATURE
		ItShallNotTick-1.0.20-build.21.jar                |It Shall Not Tick             |itshallnottick                |1.0.20-build.21     |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.134.jar               |Biomes O' Plenty              |biomesoplenty                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |DONE      |Manifest: NOSIGNATURE
		omgourd-1.18.2-3.1.0.8.jar                        |Oh My Gourd                   |omgourd                       |3.1.0.8             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		born_in_chaos_1.18_1.9.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		v1.0.1accuratebackrooms-forge1.18.2.jar           |The Accurate Backrooms        |accbackrooms                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		whisperwoods-1.18.2-2.1.0-forge.jar               |Whisperwoods                  |whisperwoods                  |1.18.2-2.1.0        |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.17.1_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.17.1             |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		extlights-4.4.jar                                 |Extended Lights               |extlights                     |4.4                 |DONE      |Manifest: NOSIGNATURE
		SlendermanV1.jar                                  |Slenderman                    |slenderman                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		InfinityMending-1.17-0.1.0.jar                    |InfinityMending               |infinitymending               |0.1.0               |DONE      |Manifest: NOSIGNATURE
		ArkysGraveyardMod_1_18_2.jar                      |Chider                        |chider001                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		GottschCore-mc1.18.2-f40.1.0-v1.9.1.jar           |GottschCore                   |gottschcore                   |1.9.1               |DONE      |Manifest: NOSIGNATURE
		modonomicon-1.18.2-1.23.2.jar                     |Modonomicon                   |modonomicon                   |1.18.2-1.23.2       |DONE      |Manifest: NOSIGNATURE
		Atlas-Lib-1.18.2-1.1.5.jar                        |Atlas Lib                     |atlaslib                      |1.1.5               |DONE      |Manifest: NOSIGNATURE
		armor-weight-1.18.2-1.0.1.jar                     |Armor Weight                  |armor_weight                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		wormhole-1.1.10-forge-mc1.18.jar                  |Wormhole (Portals)            |wormhole                      |1.1.10              |DONE      |Manifest: NOSIGNATURE
		architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |DONE      |Manifest: NOSIGNATURE
		otyacraftengine-forge-1.18.2-2.14.jar             |Otyacraft Engine              |otyacraftengine               |2.14                |DONE      |Manifest: NOSIGNATURE
		iammusicplayer-forge-1.18.2-3.16.2.jar            |Iam Music Player              |iammusicplayer                |3.16.2              |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.18.2-1.8.8.jar                        |Vampirism                     |vampirism                     |1.8.8               |DONE      |Manifest: NOSIGNATURE
		VampiresNeedUmbrellas-1.18.2-1.0.jar              |Vampires Need Umbrellas       |vampiresneedumbrellas         |1.0                 |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.18.2-1.0.0.1.jar                     |Werewolves                    |werewolves                    |1.0.0.1             |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		occultism-1.18.2-1.64.0.jar                       |Occultism                     |occultism                     |1.18.2-1.64.0       |DONE      |Manifest: NOSIGNATURE
		majrusz-library-1.18.2-2.7.3.jar                  |Majrusz Library               |majruszlib                    |2.7.3               |DONE      |Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.18.2-2.0.6.jar        |Enhanced Celestials           |enhancedcelestials            |2.0.6               |DONE      |Manifest: NOSIGNATURE
		Voidscape-1.18.2-0.2.88.jar                       |Voidscape                     |voidscape                     |1.18.2-0.2.88       |DONE      |Manifest: NOSIGNATURE
		majruszs-enchantments-1.18.2-1.6.3.jar            |Majrusz's Enchantments        |majruszsenchantments          |1.6.3               |DONE      |Manifest: NOSIGNATURE
		Sniper+mod.jar                                    |sniper mod                    |sniper_mod                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar        |Let Me Despawn                |letmedespawn                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Choo-Choo+Charles+Craft+v1.jar                    |ChooChooCharlesCraft          |choochoocharlescraft          |1.0.0               |DONE      |Manifest: NOSIGNATURE
		The+Witching+Hour.jar                             |The Witching Hour             |witching_hour                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		suszombification-1.18.2-1.2.jar                   |Suspicious Zombification      |suszombification              |1.2                 |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e589e8bd-5786-4fee-9c74-d8dac1fda39e
	FML: 40.2
	Forge: net.minecraftforge:40.2.0

**Comment by FiveNights21611** [comment]
I'll do my best to look into it, see what I can do. I'll try and let you
know if it's Client-Side, Server-Side, or Mod-Side and when I've fixed it.
Right now, I'm the only person still working on the mod.

-Main Content Developer,
                FiveNights2161

**Comment by FiveNights21611** [comment]
Does the error happen randomly, or does it happen when something specific happens in-game?

**Comment by iluvspidrs** [comment]
Thank you for looking into this! My friends appreciate it also as we love the mod.

The crash seems random, but I've had it happen when:

Hitting an enemy
Clicking on a book/crafting table
Initiating a village raid
clicking on a door
Falling into water
Shearing a sheep
Trying to place a torch.

**Comment by FiveNights21611** [comment]
Well, right now, I'm having to build the infection system from Scratch for the THIRD TIME. Yeah, the old code got corrupt when updating the mod to MCreator 2022.3. So, I'm having to entirely rebuild the infection system. So, update may take a while!

**Comment by iluvspidrs** [comment]
Yikes! That sounds so frustrating! We'll be patient, though!
